development:
    dialect: mysql
    dir: db/migrations/dev
    datasource: root:root@tcp(db)/work_management?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true

production:
    dialect: mysql
    dir: db/migrations/prod
    datasource: user_name:password@tcp(127.0.0.1)/dbname?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true